group1: # host_group
  hosts:
    host1: # host
      ansible_host: 127.0.0.1
      ansible_user: root
      _meta:
        _auth_type: IdentityAgent
        _auth_path: ~/.1password/agent.sock
        _aliases: [ "base", "another-alias" ]

    host2:
      ansible_host: 127.0.0.2
      ansible_user: manager
      ansible_password:

group2:
  hosts:
    another_host1:
      ansible_host: 172.19.0.1
      ansible_user: postgres
      ansible_password:
