name: Linter
permissions:
  contents: read

on:
  push:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock
  pull_request:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@9828f49eb4cadf267b40eaa330295c412c68c1f9 # v3.2.2
        with:
          version: ">=0.9.0"
          args: "check --verbose"
          src: "./sshgen"
