name: Linter
permissions:
  contents: read

on:
  push:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock
  pull_request:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@47de3deae877b8fcf76756bc14e8f8edd5e03e7d # v3.0.2
        with:
          version: ">=0.9.0"
          args: "check --verbose"
          src: "./sshgen"
