name: Linter
permissions:
  contents: read

on:
  push:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock
  pull_request:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@31a518504640beb4897d0b9f9e50a2a9196e75ba # v3.0.1
        with:
          version: ">=0.9.0"
          args: "check --verbose"
          src: "./sshgen"
