name: Linter

on:
  push:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock
  pull_request:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./sshgen"
          args: "--verbose"
