name: Linter
permissions:
  contents: read

on:
  push:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock
  pull_request:
    paths:
      - sshgen/**
      - tests/**
      - pyproject.toml
      - poetry.lock

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@84f83ecf9e1e15d26b7984c7ec9cf73d39ffc946 # v3.3.1
        with:
          version: ">=0.9.0"
          args: "check --verbose"
          src: "./sshgen"
