name: New release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header

  release:
    name: Build Python package
    runs-on: ubuntu-latest
    needs: generate-changelog

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Build package
        run: |
          poetry build
          ls -la dist/
        env:
          CURRENT_VERSION: ${{ github.ref_name }}

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          make_latest: true
          file_glob: true
          body: "${{ needs.generate-changelog.outputs.release_body }}"

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: release
    if: ${{ success() }}
    environment: PyPI

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Publish to PyPI
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_SSHGEN_TOKEN }}
        run: poetry publish --build
